      - name: Check secrets
        run: |
          echo "USERNAME:"
          echo "${{ secrets.DOCKER_USERNAME }}"

          echo "PASSWORD LENGTH:"
          echo -n "${{ secrets.DOCKER_PASSWORD }}" | wc -c
